#!/usr/bin/env python3
"""gen_gate.py — generate a deterministic git gate script from the rule
registry, instead of hand-writing one.

Why this exists: tools/check_git_rules.py proves the *mechanism* (a lint
gate stops the violations that prose did not, per
docs/reference/SESSION_RECORD_2026-07-25.md §9). This generator proves the
*pipeline*: a rule added to tools/rules/AGENT_RULES.yaml becomes an
enforced check with no new code. That is the shape the spec-to-gate plan
targets — the intent-to-protocol translator authors rules once, at compile
time, and what runs at the moment of action is generated deterministic
code. Parity between the generated gate and the hand-written checker is
proven by tools/tests/run_gate_parity.py against pre-registered
expectations (SPEC_TO_GATE_PREREGISTRATION.md P3).

Usage:
  python tools/gen_gate.py                # writes tools/generated/gate_git.py
  python tools/gen_gate.py --out FILE     # write elsewhere
The output file is committed; regenerate whenever AGENT_RULES.yaml changes.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from pprint import pformat

import yaml

TOOLS = Path(__file__).resolve().parent
REGISTRY = TOOLS / "rules" / "AGENT_RULES.yaml"
DEFAULT_OUT = TOOLS / "generated" / "gate_git.py"

# Subjects the git gate knows how to check; everything else in the registry
# (doc lints, workflow rules) belongs to other tools and is skipped here.
GIT_SUBJECTS = {"branch_name", "commit_message", "commit_author",
                "commit_committer", "commit_trailer"}

TEMPLATE = '''#!/usr/bin/env python3
"""gate_git.py — GENERATED by tools/gen_gate.py from tools/rules/AGENT_RULES.yaml.
Do not edit by hand; edit the registry and regenerate.

Checks not-yet-pushed commits (and the branch name) against the registry's
lint-tier git rules. Exit 0 = clean, 1 = at least one violation, each
printed with the registry's remediation text.
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
from pathlib import Path

RULES = {rules_json}

REPO = Path(__file__).resolve().parents[2]


def git(*args, repo=None):
    return subprocess.run(["git", *args], cwd=repo or REPO,
                          capture_output=True, text=True, check=True).stdout


def check_value(rule, value):
    """Return a problem string if `value` violates `rule`, else None."""
    c = rule["constraint"]
    kind = c["kind"]
    if kind == "prefix_required":
        if not value.startswith(c["value"]):
            return f"'{{value}}' does not start with '{{c['value']}}'"
    elif kind == "substring_forbidden":
        hay = value if c.get("case_sensitive") else value.lower()
        needle = c["value"] if c.get("case_sensitive") else c["value"].lower()
        if needle in hay:
            return f"forbidden substring '{{c['value']}}' in '{{value}}'"
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--range", dest="rng", default=None)
    ap.add_argument("--branch", default=None)
    ap.add_argument("--include-pushed", action="store_true")
    ap.add_argument("--repo", type=Path, default=None)
    args = ap.parse_args()
    repo = args.repo.resolve() if args.repo else REPO

    problems = []
    warnings = []

    branch = args.branch or git("rev-parse", "--abbrev-ref", "HEAD",
                                repo=repo).strip()
    platform_ok = os.environ.get("STJP_PLATFORM_BRANCH") == "1"
    if branch not in ("HEAD", "main"):
        for rule in RULES.get("branch_name", []):
            p = check_value(rule, branch)
            if p:
                msg = (f"branch: {{p}} — {{rule['remediation']}} "
                       f"[{{rule['id']}}]")
                (warnings if platform_ok else problems).append(msg)

    if args.rng:
        rng = args.rng
    else:
        try:
            git("rev-parse", "--verify", "origin/main", repo=repo)
            rng = "origin/main..HEAD"
        except subprocess.CalledProcessError:
            rng = "HEAD"
    rl = ["rev-list", rng]
    if not args.include_pushed:
        rl += ["--not", "--remotes=origin"]
    shas = [s for s in git(*rl, repo=repo).splitlines() if s]

    for sha in shas:
        short = sha[:7]
        an, ae, cn, ce = git("log", "-1",
                             "--format=%an%x00%ae%x00%cn%x00%ce", sha,
                             repo=repo).strip("\\n").split("\\x00")
        body = git("log", "-1", "--format=%B", sha, repo=repo)

        for rule in RULES.get("commit_author", []):
            c = rule["constraint"]
            if c["kind"] == "identity_required" and \\
                    (an, ae) != (c["name"], c["email"]):
                problems.append(f"{{short}}: author '{{an}} <{{ae}}>' — "
                                f"{{rule['remediation']}} [{{rule['id']}}]")
        for rule in RULES.get("commit_committer", []):
            c = rule["constraint"]
            web_flow = (cn, ce) == ("GitHub", "noreply@github.com") and \\
                (an, ae) == (c.get("name"), c.get("email"))
            if c["kind"] == "identity_required" and not web_flow and \\
                    (cn, ce) != (c["name"], c["email"]):
                problems.append(f"{{short}}: committer '{{cn}} <{{ce}}>' — "
                                f"{{rule['remediation']}} [{{rule['id']}}]")
        for rule in RULES.get("commit_message", []):
            for lineno, line in enumerate(body.splitlines(), 1):
                p = check_value(rule, line)
                if p:
                    problems.append(f"{{short}} line {{lineno}}: {{p}} — "
                                    f"{{rule['remediation']}} [{{rule['id']}}]")
        for rule in RULES.get("commit_trailer", []):
            c = rule["constraint"]
            if c["kind"] != "trailer_forbidden_except_owner":
                continue
            for m in re.finditer(
                    r"^\\s*(co-authored-by|[\\w-]*session[\\w-]*)\\s*:\\s*(.+)$",
                    body, re.IGNORECASE | re.MULTILINE):
                if not any(o.lower() in m.group(2).lower()
                           for o in c["owner_match"]):
                    problems.append(f"{{short}}: trailer "
                                    f"'{{m.group(0).strip()}}' — "
                                    f"{{rule['remediation']}} [{{rule['id']}}]")

    for w in warnings:
        print(f"WARNING: {{w}}")
    for p in problems:
        print(p)
    print(f"\\nchecked {{len(shas)}} commit(s) -> {{len(problems)}} "
          f"violation(s), {{len(warnings)}} warning(s)")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    doc = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    by_subject: dict[str, list[dict]] = {}
    skipped = []
    for rule in doc["rules"]:
        c = rule.get("constraint")
        if rule["subject"] in GIT_SUBJECTS and c and \
                c.get("kind") != "external_checker":
            by_subject.setdefault(rule["subject"], []).append(
                {"id": rule["id"], "constraint": c,
                 "remediation": rule.get("remediation") or "fix and amend"})
        else:
            skipped.append(rule["id"])

    rules_json = pformat(by_subject, width=76, sort_dicts=True)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(TEMPLATE.format(rules_json=rules_json),
                        encoding="utf-8")
    n = sum(len(v) for v in by_subject.values())
    print(f"wrote {args.out} with {n} rule(s) over "
          f"{len(by_subject)} subject(s); skipped (not git-gate scope): "
          f"{', '.join(skipped)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
